wise2ci-vip:
  image: rancher/load-balancer-service
  ports:
  - ${http_port}:80
  tty: true
  links:
  - wise2build-frontend:wise2build-frontend
  - identity-service:identity-service
  - document:document
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}
    io.rancher.loadbalancer.target.wise2build-frontend: ${http_port}=80
    io.rancher.loadbalancer.target.document: ${http_port}/document=80
    io.rancher.loadbalancer.target.identity-service: ${http_port}/api=80, ${http_port}/sockjs=80, ${http_port}/artifactory=80

consul-server:
  image: consul:0.7.0
  command: agent -server -client=0.0.0.0 -dev -node=node0 -bootstrap-expect=1 -data-dir=/tmp/consul
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}

identity-service:
  image: registry.aliyuncs.com/wisecloud/identity:2.1.44
  environment:
    PROFILE: rancher
  external_links:
  - consul-server:consul-server
  links:
  - identity-database:mysql-server

identity-database:
  image: mysql:5.5
  environment:
    MYSQL_DATABASE: identity
    MYSQL_ROOT_PASSWORD: '123456'
  stdin_open: true
  tty: true
  command:
  - mysqld
  - --character-set-server=utf8mb4
  - --collation-server=utf8mb4_unicode_ci

wise2build-frontend:
  image: registry.aliyuncs.com/wise2c/wisebuild-fronted:2.1.27-workflow
  stdin_open: true
  tty: true
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}

wise2build-biz:
  image: registry.aliyuncs.com/wise2c/build-biz:2.1.134
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  environment:
    PROFILE: rancher
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}
  links:
    - consul-server:eureka-server
    - mysql-server
    - rabbitmq
  tty: true
  stdin_open: true

mysql-server:
  image: mysql:5.5
  volumes:
  - /var/lib//biz-data-dir:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
    MYSQL_DATABASE: builderdb
  tty: true
  stdin_open: true
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}

wise2build-worker:
  image: registry.aliyuncs.com/wise2c/build-worker:2.1.65
  stdin_open: true
  tty: true
  links:
    - consul-server:eureka-server
    - rabbitmq
    - mysql-server2:mysql-server
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: wise2worker=${worker_host_label}
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /root/.jenkins/workspace:/root/.jenkins/workspace
    - /tmp:/tmp

mysql-server2:
  image: mysql:5.5
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: workerdb
  volumes:
  - /var/lib//worker-data-dir:/var/lib/mysql
  tty: true
  stdin_open: true
  command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}

document:
  labels:
    io.rancher.container.pull_image: always
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}
  tty: true
  image: registry.aliyuncs.com/wise2c/document:2.0.0
  stdin_open: true

rabbitmq:
  image: rabbitmq:3-management
  environment:
    - RABBITMQ_DEFAULT_USER=wise2c
    - RABBITMQ_DEFAULT_PASS=wise2c
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}

postgres-server:
  environment:
    POSTGRES_USER: sonar
    POSTGRES_PASSWORD: sonar
  tty: true
  image: postgres:9
  stdin_open: true
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}

sonarqube:
  environment:
    SONARQUBE_JDBC_USERNAME: sonar
    SONARQUBE_JDBC_PASSWORD: sonar
    SONARQUBE_JDBC_URL: jdbc:postgresql://postgres-server/sonar
  tty: true
  image: sonarqube:6.1
  links:
  - postgres-server:postgres-server
  stdin_open: true
  ports:
  - ${sonarqube_http_port}:9000
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}

artifactory:
  labels:
    io.rancher.scheduler.affinity:host_label: wise2biz=${biz_host_label}
  tty: true
  image: yunlzheng/artifactory-oss
  stdin_open: true
